name: Upstream Kernel with Cherry-Pick

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Add upstream kernel repository
        run: |
          git remote add upstream https://github.com/torvalds/linux.git
          git fetch upstream

      - name: Create a new branch for cherry-picking
        run: |
          git checkout -b cherry-pick-branch

      - name: Cherry-Pick Commits from Specified Repository
        run: |
          # Specify the repository and branch to cherry-pick from
          REPO="origin"  # Change this to the desired repository (e.g., "origin" or another remote)
          FEATURE_BRANCH="feature-branch"  # Change this to your actual feature branch name
          
          # Fetch the feature branch
          git fetch $REPO $FEATURE_BRANCH
          
          # Cherry-pick specific commits
          # Replace <commit-hash-1>, <commit-hash-2>, <commit-hash-3> with actual commit hashes
          for commit in <commit-hash-1> <commit-hash-2> <commit-hash-3>; do
            echo "Cherry-picking commit $commit..."
            git cherry-pick $commit || {
              echo "Cherry-pick failed for commit $commit. Continuing with next commit."
              git cherry-pick --abort  # Abort the current cherry-pick to continue with the next
            }
          done


      - name: Push changes
        run: |
          git commit -m "Enhanced kernel with custom driver and cherry-picked features" || true
          git push origin cherry-pick-branch || true
